from __future__ import annotations

ARCHIVE_EXTENSIONS = frozenset({".zip"})
PDF_EXTENSIONS = frozenset({".pdf"})
TIFF_EXTENSIONS = frozenset({".tif", ".tiff"})
HWP_EXTENSIONS = frozenset({".hwp"})

RASTER_IMAGE_EXTENSIONS = frozenset({".jpg", ".jpeg", ".png", ".bmp"})
IMAGE_EXTENSIONS = RASTER_IMAGE_EXTENSIONS | TIFF_EXTENSIONS
SUPPORTED_INPUT_EXTENSIONS = IMAGE_EXTENSIONS | PDF_EXTENSIONS | ARCHIVE_EXTENSIONS | HWP_EXTENSIONS

EDITABLE_IMAGE_EXTENSIONS = RASTER_IMAGE_EXTENSIONS
EXPANDED_CONTAINER_EXTENSIONS = PDF_EXTENSIONS | TIFF_EXTENSIONS
